web:
  upload-path: ./src/main/resources/upload/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mmall?characterEncoding=utf-8
    username: root
    password: root
  resources:
    static-locations: classpath:/resources/,classpath:/static/,file:${web.upload-path}
  redis:
    host: 127.0.0.1
    port: 6379
    password: Gloria
  rabbitmq:
    username: XXX
    password: xxx
    virtual-host: xx
    addresses: xx
mybatis:
  mapper-locations: classpath*:mappers/*.xml