web:
  upload-path: ./src/main/resources/upload/
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mmall?characterEncoding=utf-8
    username: root
    password: root
  resources:
    static-locations: classpath:/resources/,classpath:/static/,file:${web.upload-path}
  redis:
    host: 127.0.0.1
    port: 6379
    password: Gloria
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  dubbo:
    application:
      name: dubbo_consumer
      registry:
        address: zookeeper://127.0.0.1:2181
      protocol:
        name: dubbo
        port: 20880
      scan: com.sboot.springboot.service
mybatis:
  mapper-locations: classpath*:mappers/*.xml